spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vibe_db
    username: dev_user
    password: dev_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082
